name: Go CI

on:
  pull_request:
  push:
    branches: [ "main" ]   # or your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go from go.mod
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'   # <- reads 1.24.2 automatically

    - name: Cache Go modules & build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Run unit tests
      run: |
        go test -race -covermode=atomic -coverprofile=coverage.out -tags=unit ./...

    - name: Upload coverage artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage.out
